
Vagrant.configure('2') do |config|
  config.vm.define 'example1' do |c|
    c.vm.box = 'ubuntu/trusty64'
    c.vm.network :private_network, ip: '192.168.88.25'
    c.vm.network :forwarded_port, guest: 80, host: 8080
    c.vm.hostname = 'example.local'
    c.vm.provision 'ansible' do |ansible|
      ansible.playbook = 'main.yml'
      ansible.sudo = true
      ansible.inventory_path = 'vagrant-hosts.ini'
      ansible.host_key_checking = false
      ansible.limit = 'app'
    end
  end
end

